### ISSUE TITLE
How to run it in batch size for faster convergence

### ISSUE THREAD

**Issue by dujijun007** [Sleepwalking/pytorch-softdtw#2]
Thanks for your contribution, if you can solve my problem I'll be grateful!

**Comment by Sleepwalking** [comment]
If your inputs are of the same length, then adding a batch dimension to all PyTorch and Numpy tensors should work (e.g. changing `R[i, j + 1]` to `R[:, i, j + 1]`). Otherwise, it will be tricky to define DTW over sequences of different lengths. I guess the only way is to sequentially run the SoftDTW operator over the batch.
